name: Contents deployment

on:
  push:
    branches:
      - main

jobs:
  contents-deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "public/Contents/*"
          target: ${{ secrets.SSH_TARGET }}
          strip_components: 2
          overwrite: true
